default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
 <<: *default
 database: db/chatroom_development
 host: localhost

test:
 <<: *default
 database: db/chatroom_test
 host: localhost

production:
 <<: *default
 database: chatroom_production
 username: chatroom
 password: <%= ENV['CHATROOM_DATABASE_PASSWORD'] %>
